#!/bin/bash
# Commandes utiles pour gérer le projet Spark Trend Analyzer

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║           Spark Trend Analyzer - Commandes Utiles                 ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

# Alias et raccourcis
alias spark-start='./start.sh'
alias spark-test='python test_api.py'
alias spark-verify='python verify_project.py'
alias spark-docs='open http://localhost:8000/docs 2>/dev/null || echo "http://localhost:8000/docs"'
alias spark-ui='open http://localhost:8000/ui 2>/dev/null || echo "http://localhost:8000/ui"'

echo "✅ Alias créés. Vous pouvez maintenant utiliser:"
echo ""
echo "  spark-start      → Démarrer le serveur"
echo "  spark-test       → Lancer les tests"
echo "  spark-verify     → Vérifier l'intégrité"
echo "  spark-docs       → Ouvrir la documentation API"
echo "  spark-ui         → Ouvrir l'interface web"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Commandes manuelles:"
echo ""
echo "1️⃣  Configuration:"
echo "    cp .env.example .env"
echo "    nano .env"
echo ""
echo "2️⃣  Installation:"
echo "    pip install -r requirements-openai.txt"
echo ""
echo "3️⃣  Démarrage:"
echo "    ./start.sh"
echo "    # ou"
echo "    uvicorn api_server:app --reload --host 0.0.0.0 --port 8000"
echo ""
echo "4️⃣  Tests:"
echo "    python test_api.py                    # Tests API"
echo "    python verify_project.py              # Vérifier intégrité"
echo ""
echo "5️⃣  Accès:"
echo "    http://localhost:8000/ui              # Interface web"
echo "    http://localhost:8000/docs            # API Documentation"
echo "    http://localhost:8000/health          # Health check"
echo ""
echo "6️⃣  Exemples avec curl:"
echo ""
echo "    # Health check"
echo "    curl http://localhost:8000/health"
echo ""
echo "    # Configuration"
echo "    curl http://localhost:8000/config"
echo ""
echo "    # Créer une analyse"
echo "    curl -X POST http://localhost:8000/api/v1/analyze \\"
echo "      -H 'Content-Type: application/json' \\"
echo "      -d '{\"prompt\": \"Vérifie les tendances de splio.users pour le 20260121\"}'"
echo ""
echo "    # Récupérer les jobs"
echo "    curl http://localhost:8000/api/v1/jobs?limit=20"
echo ""
echo "    # Status d'un job"
echo "    curl http://localhost:8000/api/v1/jobs/{job_id}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 Documentation:"
echo "    • QUICKSTART.md  - Démarrage rapide"
echo "    • SETUP.md       - Configuration détaillée"
echo "    • CORRECTIONS.md - Corrections appliquées"
echo "    • STATUS.md      - Status du projet"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
